# Generated by Django 4.1 on 2022-09-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='game', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
